// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_Sentro.Data;

#nullable disable

namespace WEB_Sentro.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222100000_AddAttachments")]
    partial class AddAttachments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_Sentro.Data.Entities.Attachment", b =>
            {
                b.Property<int>("AttachmentId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));
                b.Property<string>("FileRef").HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<string>("FileName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("OrgId").HasColumnType("int");
                b.Property<int>("RiskId").HasColumnType("int");
                b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
                b.Property<string>("UploadedByUserId").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("AttachmentId");
                b.HasIndex("RiskId");
                b.ToTable("Attachments", (string)null);
                b.HasOne("WEB_Sentro.Data.Entities.Risk", "Risk")
                    .WithMany("Attachments")
                    .HasForeignKey("RiskId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
